/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as ToolsVulnerabilityScannerRouteImport } from './routes/tools.vulnerability-scanner'
import { Route as ToolsSslAnalyzerRouteImport } from './routes/tools.ssl-analyzer'
import { Route as ToolsPortScannerRouteImport } from './routes/tools.port-scanner'
import { Route as ToolsPasswordStrengthRouteImport } from './routes/tools.password-strength'
import { Route as ToolsDnsLookupRouteImport } from './routes/tools.dns-lookup'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsVulnerabilityScannerRoute =
  ToolsVulnerabilityScannerRouteImport.update({
    id: '/tools/vulnerability-scanner',
    path: '/tools/vulnerability-scanner',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsSslAnalyzerRoute = ToolsSslAnalyzerRouteImport.update({
  id: '/tools/ssl-analyzer',
  path: '/tools/ssl-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPortScannerRoute = ToolsPortScannerRouteImport.update({
  id: '/tools/port-scanner',
  path: '/tools/port-scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPasswordStrengthRoute = ToolsPasswordStrengthRouteImport.update({
  id: '/tools/password-strength',
  path: '/tools/password-strength',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsDnsLookupRoute = ToolsDnsLookupRouteImport.update({
  id: '/tools/dns-lookup',
  path: '/tools/dns-lookup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/tools/dns-lookup': typeof ToolsDnsLookupRoute
  '/tools/password-strength': typeof ToolsPasswordStrengthRoute
  '/tools/port-scanner': typeof ToolsPortScannerRoute
  '/tools/ssl-analyzer': typeof ToolsSslAnalyzerRoute
  '/tools/vulnerability-scanner': typeof ToolsVulnerabilityScannerRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/tools/dns-lookup': typeof ToolsDnsLookupRoute
  '/tools/password-strength': typeof ToolsPasswordStrengthRoute
  '/tools/port-scanner': typeof ToolsPortScannerRoute
  '/tools/ssl-analyzer': typeof ToolsSslAnalyzerRoute
  '/tools/vulnerability-scanner': typeof ToolsVulnerabilityScannerRoute
  '/tools': typeof ToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/tools/dns-lookup': typeof ToolsDnsLookupRoute
  '/tools/password-strength': typeof ToolsPasswordStrengthRoute
  '/tools/port-scanner': typeof ToolsPortScannerRoute
  '/tools/ssl-analyzer': typeof ToolsSslAnalyzerRoute
  '/tools/vulnerability-scanner': typeof ToolsVulnerabilityScannerRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/tools/dns-lookup'
    | '/tools/password-strength'
    | '/tools/port-scanner'
    | '/tools/ssl-analyzer'
    | '/tools/vulnerability-scanner'
    | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/tools/dns-lookup'
    | '/tools/password-strength'
    | '/tools/port-scanner'
    | '/tools/ssl-analyzer'
    | '/tools/vulnerability-scanner'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/tools/dns-lookup'
    | '/tools/password-strength'
    | '/tools/port-scanner'
    | '/tools/ssl-analyzer'
    | '/tools/vulnerability-scanner'
    | '/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ToolsDnsLookupRoute: typeof ToolsDnsLookupRoute
  ToolsPasswordStrengthRoute: typeof ToolsPasswordStrengthRoute
  ToolsPortScannerRoute: typeof ToolsPortScannerRoute
  ToolsSslAnalyzerRoute: typeof ToolsSslAnalyzerRoute
  ToolsVulnerabilityScannerRoute: typeof ToolsVulnerabilityScannerRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/vulnerability-scanner': {
      id: '/tools/vulnerability-scanner'
      path: '/tools/vulnerability-scanner'
      fullPath: '/tools/vulnerability-scanner'
      preLoaderRoute: typeof ToolsVulnerabilityScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/ssl-analyzer': {
      id: '/tools/ssl-analyzer'
      path: '/tools/ssl-analyzer'
      fullPath: '/tools/ssl-analyzer'
      preLoaderRoute: typeof ToolsSslAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/port-scanner': {
      id: '/tools/port-scanner'
      path: '/tools/port-scanner'
      fullPath: '/tools/port-scanner'
      preLoaderRoute: typeof ToolsPortScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/password-strength': {
      id: '/tools/password-strength'
      path: '/tools/password-strength'
      fullPath: '/tools/password-strength'
      preLoaderRoute: typeof ToolsPasswordStrengthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/dns-lookup': {
      id: '/tools/dns-lookup'
      path: '/tools/dns-lookup'
      fullPath: '/tools/dns-lookup'
      preLoaderRoute: typeof ToolsDnsLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ToolsDnsLookupRoute: ToolsDnsLookupRoute,
  ToolsPasswordStrengthRoute: ToolsPasswordStrengthRoute,
  ToolsPortScannerRoute: ToolsPortScannerRoute,
  ToolsSslAnalyzerRoute: ToolsSslAnalyzerRoute,
  ToolsVulnerabilityScannerRoute: ToolsVulnerabilityScannerRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
